site_name: Документация для отдела "Информационные технологии"


nav:
  - Техническое задание:
    - ts/index.md
  - Руководство пользователя:
    - ug/index.md
  - Руководство программиста:
    - pg/index.md
   



theme:
  name: material
  logo: assets/iconNNGF.png
  favicon: assets/iconNNGF.png
  language: ru
  plugins:
    - search:
        lang: 
          - en
          - ru
    
        
  
  
  
  
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Ночь
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: День
  features:
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
  